### ISSUE TITLE
Support for cygwin (with proposed solution)

### ISSUE THREAD

**Issue by jpc4242** [sio/Makefile.venv#2]
I had to replace the block where OS is detected in order to support cygwin.
I believed that the following doesn't break anything, but you may want to double check before doing the change:
```make
VENV=$(VENVDIR)/bin
EXE=
ifdef OS  # Windows support
ifneq ($(shell echo $$OSTYPE),cygwin) #Cygwin support
VENV=$(VENVDIR)/Scripts
EXE=.exe
endif #OSTYPE
endif #OS
```

**Comment by sio** [comment]
Thank you for reporting this! I will review your approach and will look for a better way of detecting Windows when I'll get back from a vacation (after December, 1st)

**Comment by sio** [comment]
Hello again!

I am totally unfamiliar with Cygwin - @jpc4242, can you explain the logic to me? Your changes imply that Cygwin uses executable names without `.exe` extension and that Python in Cygwin follows Unix-like filesystem layout. Is that correct?

Some [random page](https://www.davidbaumgold.com/tutorials/set-up-python-windows/) from Google shows that some people use vanilla Windows Python installer in Cygwin environment. I assume in that case Python would behave the same as without Cygwin - it means the workaround needs to be more robust, maybe an env flag to skip Windows detection altogether?

**Comment by sio** [comment]
@jpc4242, I've just pushed some changes to `develop` - I added an environment variable to skip Windows detection. I've tested it in Cygwin, seems to work fine. Please try it :)

**Comment by jpc4242** [comment]
Thanks, I tested it and it worked like a charm provided I set the new variable
```makefile
FORCE_UNIX_PATHS=y
include Makefile.venv
```
I think that he issue may be closed

**Comment by sio** [comment]
Thank you, your solution is very clever. That way we avoid the inconsistencies I've mentioned earlier (running native Python from Cygwin shell).

I've added your code to `develop`, CI tests on all platforms seem fine. I'll merge it to `master` later today

**Comment by sio** [comment]
Merged to `master`.
