### ISSUE TITLE
Spaces in path fatally confuse the script

### ISSUE THREAD

**Issue by MinhHaDuong** [sio/Makefile.venv#5]
Hi,
  Thanks for the code. I had to replace spaces by underscore in my project directory name to make it work properly.
Minh 

![Fragility to space in dirname](https://user-images.githubusercontent.com/18475208/80282483-1766de00-8712-11ea-8c71-081f2b5bd0cd.png)

**Comment by sio** [comment]
Well, GNU Make really can't handle whitespace in filenames, so it's not just my script. I'll see if there if there are ways to lessen the destructive behavior, but you should probably consider such filepaths unsupported. I'll make a note of it in the README

**Comment by MinhHaDuong** [comment]
Got it. Why is it that WORKDIR must be an absolute path ?

**Comment by sio** [comment]
Good catch!

That decision does not make much sense now. When this Makefile was first written it was used to build a single specific project. Absolute path to WORKDIR is a legacy limitation that was sensible to that one project but should have been dropped when I was splitting recipes for a generic Makefile.venv

I'll remove that conversion and check if of any tests fail - they probably will not. I'll probably have free time for that this weekend.

Adding that change will probably fix the issue you've encountered, but you should still be cautious when mixing `make` and whitespaced filepaths - it's destined to break :-)

**Comment by sio** [comment]
I removed absolute path requirement for WORKDIR and added a note about spaces in filepaths to README. See the latest release.

**Comment by MinhHaDuong** [comment]
Thanks again.
