### ISSUE TITLE
Error when overriding the VENVDIR

### ISSUE THREAD

**Issue by simaoafonso-pwt** [sio/Makefile.venv#6]
I want to override the virtual environment dir to include the Python version on the path.

Here's the relevant part of my Makefile:

```make
PYTHON_VERSION := 3.7
PY := python$(PYTHON_VERSION)
VENVDIR := .venv/$(PYTHON_VERSION)
include release/Makefile.venv
```

And here is the output for a simple command

```
$ make show-venv
release/Makefile.venv:134: warning: overriding recipe for target '.venv/3.7'
release/Makefile.venv:129: warning: ignoring old recipe for target '.venv/3.7'
release/Makefile.venv:174: warning: overriding recipe for target '.venv/3.7'
release/Makefile.venv:134: warning: ignoring old recipe for target '.venv/3.7'
release/Makefile.venv:173: *** mixed implicit and normal rules: deprecated syntax
make: Circular .venv/3.7 <- .venv/3.7 dependency dropped.
make: Circular /bin/.initialized-with-Makefile.venv <- .venv/3.7 dependency dropped.
.venv/3.7  /bin/pip install -r requirements.txt
make: .venv/3.7: No such file or directory
make: *** [release/Makefile.venv:134: /bin/.initialized-with-Makefile.venv] Error 127
```

Hardcoding the `VENVDIR` without variables doesn't help, and neither does turning it into a regular variable (`VENVDIR = .venv/3.7`).
Maybe I'm doing something wrong?

I'm using version "v2020.05.05"

**Comment by simaoafonso-pwt** [comment]
I get similar results if I override the `WORKDIR` variable.

**Comment by simaoafonso-pwt** [comment]
> Hardcoding the `VENVDIR` without variables doesn't help, and neither does turning it into a regular variable (`VENVDIR = .venv/3.7`).
> Maybe I'm doing something wrong?

Yeah, I'm testing it wrong.

Using `VENVDIR := .venv/3.7` works. Adding variables to `VENVDIR` or `WORKDIR` borks it.
I think I tested all possible combinations of `:=` and `=` variables.

**Comment by sio** [comment]
I've just tested your example with no other lines in `Makefile`:

```Makefile
PYTHON_VERSION := 3.7
PY := python$(PYTHON_VERSION)
VENVDIR := .venv/$(PYTHON_VERSION)

include Makefile.venv
```

It works correctly both with immediate assignment (`:=`) and with delayed assignment (`=`).

I suspect that the problem is in the part of your Makefile you've skipped. You probably provide a  colliding recipe for `.venv` or `.venv/3.7` or something like that.

**Comment by sio** [comment]
Also, is it possible that you've pasted the `include` stanza twice?

What OS are you running this on?

**Comment by simaoafonso-pwt** [comment]
I'm running on Arch Linux.

```
$  make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by simaoafonso-pwt** [comment]
Found the issue, I had a comment on the same line as the `PYTHON_VERSION` variable.

Sorry about this, I'm dumb.

**Comment by sio** [comment]
4.3 is quite new. I haven't encountered it yet. Will check now.

**Comment by sio** [comment]
Ah!.. So PYTHON_VERSION value contained trailing whitespace :) Yeah, GNU Make is quirky like that.

I'm glad you found the problem

**Comment by simaoafonso-pwt** [comment]
> Ah!.. So PYTHON_VERSION value contained trailing whitespace :) Yeah, GNU Make is quirky like that.
> 
> I'm glad you found the problem

Yeah, my Make-fu failed there. Thanks.

**Comment by sio** [comment]
I've added `debug-venv` target to help in troubleshooting similar issues.
